// 物理公式101選 完全マスターデータ
const PHYSICS_FORMULAS = [
    // ==========================================
    // 1. 力学（No.1 〜 No.41）
    // ==========================================
    { id: 1, category: "力学", name: "平均の速度", formula: "v = Δx / Δt", desc: "位置の変化量（変位）を、それにかかった時間で割った速度の基本定義です。", unit: "m/s" },
    { id: 2, category: "力学", name: "平均の加速度", formula: "a = Δv / Δt", desc: "単位時間あたりに、速度がどれだけ変化したかを表す割合です。", unit: "m/s²" },
    { id: 3, category: "力学", name: "等加速度直線運動（速度）", formula: "v = v₀ + at", desc: "初速度 v₀ に、経過時間と加速度の積を足して未来の速度を求めます。", unit: "m/s" },
    { id: 4, category: "力学", name: "等加速度直線運動（変位）", formula: "x = v₀t + (1/2)at²", desc: "加速しながら進む物体が、時間 t 秒間で移動する距離（位置）を求めます。", unit: "m" },
    { id: 5, category: "力学", name: "等加速度直線運動（時間なし）", formula: "v² - v₀² = 2ax", unit: "-", desc: "時間tを含まない速度と変位の関係。計算を時短できます。", unit: "なし" },
    { id: 6, category: "力学", name: "自由落下（速度）", formula: "v = gt", desc: "初速度0で落下した時間t後の速度。加速度は重力加速度 g です。", unit: "m/s" },
    { id: 7, category: "力学", name: "自由落下（変位）", formula: "y = (1/2)gt²", unit: "m", desc: "初速度0で落下した時間t後の落下距離（高さ）を求めます。", unit: "m" },
    { id: 8, category: "力学", name: "鉛直投げ下ろし（速度）", formula: "v = v₀ + gt", desc: "下向きに初速 v₀ を与えて投げた物体の速度です。重力でどんどん加速します。", unit: "m/s" },
    { id: 9, category: "力学", name: "鉛直投げ下ろし（変位）", formula: "y = v₀t + (1/2)gt²", unit: "m", desc: "下向きに投げ下ろした物体が、時間 t 秒間で進む落下距離です。", unit: "m" },
    { id: 10, category: "力学", name: "鉛直投げ上げ（速度）", formula: "v = v₀ - gt", desc: "上向きに投げ上げた物体の速度。重力に逆らうため徐々に減速します。", unit: "m/s" },
    { id: 11, category: "力学", name: "鉛直投げ上げ（変位）", formula: "y = v₀t - (1/2)gt²", desc: "上向きに投げ上げた物体の高さです。最高点に達した後は落下します。", unit: "m" },
    { id: 12, category: "力学", name: "斜方投射（水平位置）", formula: "x = v₀ cosθ · t", desc: "【実験1連動】斜めに投げた物体の横方向の動き。水平には力が働かないため等速です。", unit: "m" },
    { id: 13, category: "力学", name: "斜方投射（鉛直位置）", formula: "y = v₀ sinθ · t - (1/2)gt²", desc: "【実験1連動】斜めに投げた物体の縦方向の動き。投げ上げと同じ放物線を描きます。", unit: "m" },
    { id: 14, category: "力学", name: "フックの法則", formula: "F = kx", desc: "【実験2連動】ばねの弾性力。伸びや縮み x に比例した大きさの力が復元力として働きます。", unit: "N" },
    { id: 15, category: "力学", name: "運動方程式", formula: "ma = F", desc: "質量 m、加速度 a、受ける力 F の関係。物理学の基盤となる超重要数式です。", unit: "N" },
    { id: 16, category: "力学", name: "重力の大きさ", formula: "W = mg", desc: "質量 m の物体が、地球の重力加速度 g によって引きつけられる力の大きさです。", unit: "N" },
    { id: 17, category: "力学", name: "最大静止摩擦力", formula: "F_max = μN", desc: "物体が動き出す直前の摩擦力の上限値。μは静止摩擦係数、Nは垂直抗力です。", unit: "N" },
    { id: 18, category: "力学", name: "動摩擦力", formula: "F' = μ'N", desc: "滑っている物体にはたらく摩擦力。速度に関わらずほぼ一定になります。", unit: "N" },
    { id: 19, category: "力学", name: "圧力の定義", formula: "P = F / S", desc: "単位面積（1平方メートル）あたりに、垂直に押し付けられる力の大きさです。", unit: "Pa" },
    { id: 20, category: "力学", name: "水圧", formula: "P = ρhg", desc: "深さ h における流体の圧力。ρは密度。大気圧を考慮する場合は足します。", unit: "Pa" },
    { id: 21, category: "力学", name: "浮力（アルキメデスの原理）", formula: "F = ρVg", desc: "流体中の物体が受ける上向きの力。物体が排除した流体の重さに等しいです。", unit: "N" },
    { id: 22, category: "力学", name: "力のモーメント", formula: "M = Fl", desc: "物体を回転させる能力の大きさ。力 F と、腕の長さ l の積で決まります。", unit: "N·m" },
    { id: 23, category: "力学", name: "ふたつの物体の重心", formula: "x_G = (m₁x₁ + m₂x₂) / (m₁ + m₂)", desc: "質量が異なる2つの物体の、全体の釣り合いが取れる中心位置です。", unit: "m" },
    { id: 24, category: "力学", name: "運動量", formula: "p = mv", desc: "物体の「勢い」を表す量。質量と速度の積になります。", unit: "kg·m/s" },
    { id: 25, category: "力学", name: "力積", formula: "I = FΔt", desc: "物体に与えた「衝撃」の量。加えた力 F と、その時間の積です。", unit: "N·s" },
    { id: 26, category: "力学", name: "運動量変化と力積の関係", formula: "mv' - mv = FΔt", desc: "物体に力積（衝撃）を与えると、その分だけ物体の運動量（勢い）が変化します。", unit: "なし" },
    { id: 27, category: "力学", name: "運動量保存則", formula: "m₁v₁ + m₂v₂ = m₁v₁' + m₂v₂'", desc: "衝突や分裂の前後で、外力が働かない限り、全体の運動量の総和は不変です。", unit: "なし" },
    { id: 28, category: "力学", name: "反発係数（はねかえり係数）", formula: "e = - (v₁' - v₂') / (v₁ - v₂)", unit: "-", desc: "衝突前後の相対速度の比。0から1の間の値をとります。", unit: "なし" },
    { id: 29, category: "力学", name: "仕事の定義", formula: "W = Fs cosθ", desc: "力 F を加え、その向きからθずれた方向に s 移動させた仕事。単位はジュール。", unit: "J" },
    { id: 30, category: "力学", name: "仕事率", formula: "P = W / t", desc: "1秒あたりにどれだけの仕事（エネルギー消費）をしたかという効率です。", unit: "W" },
    { id: 31, category: "力学", name: "運動エネルギー", formula: "K = (1/2)mv²", desc: "動いている物体が持つエネルギー。速度の2乗に比例します。", unit: "J" },
    { id: 32, category: "力学", name: "重力による位置エネルギー", formula: "U = mgh", desc: "高い場所にある物体が持つ潜在的なエネルギー。基準面からの高さに比例します。", unit: "J" },
    { id: 33, category: "力学", name: "弾性力による位置エネルギー", formula: "U = (1/2)kx²", desc: "ばねの伸び縮みxによって蓄えられているエネルギーです。", unit: "J" },
    { id: 34, category: "力学", name: "力学的エネルギー保存則", formula: "K₁ + U₁ = K₂ + U₂", desc: "摩擦や空気抵抗がない場合、運動エネルギーと位置エネルギーの和は常に一定です。", unit: "なし" },
    { id: 35, category: "力学", name: "角速度の定義", formula: "ω = θ / t", desc: "円運動において、物体が1秒あたりに進む回転角度（ラジアン）を表します。", unit: "rad/s" },
    { id: 36, category: "力学", name: "速度と角速度の関係", formula: "v = rω", desc: "円運動の接線方向の速度。回転半径 r が大きいほど、外側の速度は速くなります。", unit: "m/s" },
    { id: 37, category: "力学", name: "向心加速度", formula: "a = rω² = v² / r", desc: "円運動の中心方向へはたらく加速度。常に進行方向を曲げ続けます。", unit: "m/s²" },
    { id: 38, category: "力学", name: "向心力", formula: "F = mrω²", desc: "円運動を維持するために必要な、中心向きの力。運動方程式に(37)を代入した形です。", unit: "N" },
    { id: 39, category: "力学", name: "ばね振り子の周期", formula: "T = 2π√(m / k)", desc: "【実験2連動】ばねに吊るしたおもりの単振動周期。重力の影響を受けません。", unit: "s" },
    { id: 40, category: "力学", name: "単振り子の周期", formula: "T = 2π√(l / g)", desc: "糸で吊るしたおもりの振幅が小さいときの周期。おもりの重さには関係しません。", unit: "s" },
    { id: 41, category: "力学", name: "万有引力の法則", formula: "F = G(Mm / r²)", desc: "【実験4連動】全物質が引き合う宇宙の力。質量に比例し、距離の2乗に反比例します。", unit: "N" },

    // ==========================================
    // 2. 熱力学（No.42 〜 No.53）
    // ==========================================
    { id: 42, category: "熱力学", name: "熱量と熱容量", formula: "Q = CΔT", desc: "物体全体の温度を ΔT 変化させるのに必要な熱量 Q を求めます。", unit: "J" },
    { id: 43, category: "熱力学", name: "熱量と比熱", formula: "Q = mcΔT", desc: "物質 1g の温度を1度上げるのに必要な固有の熱量（比熱 c）を用いた式です。", unit: "J" },
    { id: 44, category: "熱力学", name: "熱膨張", formula: "l = l₀(1 + αt)", desc: "温度上昇tによる長さの変化。αは線膨張率です。", unit: "m" },
    { id: 45, category: "熱力学", name: "ボイルの法則", formula: "P V = 一定", desc: "温度が一定のとき、気体の圧力 P と体積 V は反比例します。", unit: "なし" },
    { id: 46, category: "熱力学", name: "シャルルの法則", formula: "V / T = 一定", desc: "圧力が一定のとき、気体の体積 V は絶対温度 T に比例して膨張します。", unit: "なし" },
    { id: 47, category: "熱力学", name: "理想気体の状態方程式", formula: "P V = n R T", desc: "気体のマクロな状態（P, V, T）と、気体粒子の量（n:モル）を結ぶ式です。", unit: "なし" },
    { id: 48, category: "熱力学", name: "気体分子の平均運動エネルギー", formula: "(1/2)mv² = (3/2)kT", desc: "分子1個あたりの熱運動エネルギーは、絶対温度 T のみで決まります。", unit: "J" },
    { id: 49, category: "熱力学", name: "単原子分子理想気体の内部エネルギー", formula: "U = (3/2)nRT", desc: "気体全体が内部に閉じ込めている熱エネルギーの総量。温度にのみ比例します。", unit: "J" },
    { id: 50, category: "熱力学", name: "熱力学第一法則", formula: "ΔU = Q + W", desc: "内部エネルギーの変化は、吸収した熱量 Q と、外部からされた仕事 W の和です。", unit: "J" },
    { id: 51, category: "熱力学", name: "定圧変化の仕事", formula: "W = P ΔV", desc: "圧力を保ったまま気体が膨張したとき、外部に対して気体がこなした仕事です。", unit: "J" },
    { id: 52, category: "熱力学", name: "マイヤーの関係式", formula: "C_p - C_v = R", desc: "定圧モル比熱C_pと定積モル比熱C_vの差は気体定数Rに等しいです。", unit: "J/(mol·K)" },
    { id: 53, category: "熱力学", name: "熱効率", formula: "e = W / Q₁", desc: "吸収した熱量 Q₁ のうち、何パーセントを有効な仕事 W に変換できたかの割合です。", unit: "なし" },

    // ==========================================
    // 3. 波動（No.54 〜 No.69）
    // ==========================================
    { id: 54, category: "波動", name: "波の基本式", formula: "v = f λ", desc: "波の進む速度。1秒の振動数 f と、波1個の長さ（波長 λ）の積になります。", unit: "m/s" },
    { id: 55, category: "波動", name: "周期と振動数", formula: "T = 1 / f", desc: "波が1回振動する時間 T と、1秒間の振動回数 f は逆数の関係です。", unit: "s" },
    { id: 56, category: "波動", name: "屈折の法則", formula: "sin i / sin r = v₁ / v₂ = n₁₂", desc: "異なる媒体に進む波の入射角iと屈折角rの関係。速度比と等しいです。", unit: "なし" },
    { id: 57, category: "波動", name: "絶対屈折率", formula: "n = c / v", desc: "真空中の光速 c に対し、その物質中でどれだけ光が減速するかを示す指標です。", unit: "なし" },
    { id: 58, category: "波動", name: "全反射の臨界角", formula: "sin i_0 = n₂ / n₁", unit: "-", desc: "屈折率が大きい媒質n₁から小さい媒質n₂へ向かうとき全反射が起きる最小の入射角です。", unit: "なし" },
    { id: 59, category: "波動", name: "うなりの振動数", formula: "f = |f₁ - f₂|", desc: "周波数がわずかに異なる2つの音を同時に鳴らしたとき、1秒間に聞こえる強弱の回数です。", unit: "Hz" },
    { id: 60, category: "波動", name: "弦を伝わる波の速さ", formula: "v = √(S / ρ)", desc: "弦を伝わる横波の速度。張力 S が強く、線密度 ρ が小さいほど速くなります。", unit: "m/s" },
    { id: 61, category: "波動", name: "弦の固有振動数", formula: "f_n = n(v / 2L)", desc: "両端を固定した長さ L の弦が共鳴するときの、基本・倍音の振動数です。", unit: "Hz" },
    { id: 62, category: "波動", name: "閉管の固有振動数", formula: "f_n = (2k-1)(v / 4L)", desc: "片方が閉じた筒（空気柱）が共鳴する周波数（kは整数）。奇数倍音のみ発生。", unit: "Hz" },
    { id: 63, category: "波動", name: "開管の固有振動数", formula: "f_n = n(v / 2L)", desc: "両端が開いた筒（空気柱）が共鳴する周波数。全整数倍音が発生します。", unit: "Hz" },
    { id: 64, category: "波動", name: "音速（気温依存）", formula: "V = 331.5 + 0.6t", unit: "m/s", desc: "摂氏t度における空気中の音の速さを求める近似式です。", unit: "m/s" },
    { id: 65, category: "波動", name: "ドップラー効果", formula: "f' = f · (V - v_o) / (V - v_s)", desc: "音源（v_s）や観測者（v_o）が動くことで、聞こえる音の高さ f' が変化します。", unit: "Hz" },
    { id: 66, category: "波動", name: "凸レンズの公式", formula: "1/a + 1/b = 1/f", desc: "物体までの距離 a、像までの距離 b、焦点距離 f の関係。実像・虚像で符合に注意。", unit: "なし" },
    { id: 67, category: "波動", name: "レンズの倍率", formula: "m = |b / a|", desc: "元の物体の大きさに対し、像が何倍に拡大（縮小）されるかの比率です。", unit: "なし" },
    { id: 68, category: "波動", name: "ヤングの実験（明線条件）", formula: "d x / L = m λ", desc: "スリット間隔d、距離Lのときのスクリーン上の明線の位置x（mは整数）です。", unit: "なし" },
    { id: 69, category: "波動", name: "回折格子（明線条件）", formula: "d sinθ = m λ", desc: "格子定数 d の回折格子で、特定の角度 θ で光が強め合う条件です。", unit: "なし" },

    // ==========================================
    // 4. 電磁気（No.70 〜 No.91）
    // ==========================================
    { id: 70, category: "電磁気", name: "クーロンの法則（静電気力）", formula: "F = k(q₁q₂ / r²)", desc: "【実験5連動】電荷同士に働く引き合う・退け合う力。距離の2乗に反比例します。", unit: "N" },
    { id: 71, category: "電磁気", name: "電場の定義", formula: "E = F / q", desc: "空間の電気的な強さ。ここに 1C の電荷を置いたときに受ける力です。", unit: "N/C" },
    { id: 72, category: "電磁気", name: "点電荷が作る電場", formula: "E = k(Q / r²)", desc: "点電荷 Q から距離 r 離れた地点に形成される電場の強さを計算します。", unit: "N/C" },
    { id: 73, category: "電磁気", name: "電位の定義", formula: "V = U / q", desc: "電気的な「高さ」。1C の正電荷が持つ静電エネルギーです。", unit: "V" },
    { id: 74, category: "電磁気", name: "点電荷による電位", formula: "V = k(Q / r)", desc: "点電荷 Q の周囲の電気的な山の高さ。距離に反比例します。", unit: "V" },
    { id: 75, category: "電磁気", name: "一様電場と電位の関係", formula: "V = Ed", desc: "並行板コンデンサー内部など均一な電場における、電圧 V と距離 d の関係です。", unit: "V" },
    { id: 76, category: "電磁気", name: "電気容量の定義", formula: "Q = C V", desc: "コンデンサーに、電圧 V をかけたときに蓄えられる電荷 Q の量を示します。", unit: "C" },
    { id: 77, category: "電磁気", name: "平行板コンデンサーの容量", formula: "C = ε(S / d)", desc: "極板面積 S に比例し、板の間隔 d に反比例する、コンデンサーの性能式です。", unit: "F" },
    { id: 78, category: "電磁気", name: "静電エネルギー", formula: "U = (1/2)C V²", desc: "電荷を溜め込んだコンデンサーが内部に蓄えているエネルギーです。", unit: "J" },
    { id: 79, category: "電磁気", name: "コンデンサーの並列合成", formula: "C = C₁ + C₂", desc: "並列に繋ぐと、全体の容量は個々の容量の和になります。", unit: "F" },
    { id: 80, category: "電磁気", name: "コンデンサーの直列合成", formula: "1/C = 1/C₁ + 1/C₂", desc: "直列に繋ぐと、全体の容量は個々の容量より小さくなります。", unit: "F" },
    { id: 81, category: "電磁気", name: "電流の定義", formula: "I = q / t", desc: "回路を、1秒間に通過する電気量（q）を表します。", unit: "A" },
    { id: 82, category: "電磁気", name: "オームの法則", formula: "V = RI", desc: "抵抗 R に電流 I を流すために必要な電圧 V の基本関係式です。", unit: "V" },
    { id: 83, category: "電磁気", name: "抵抗率と抵抗", formula: "R = ρ(l / S)", desc: "導線の電気抵抗。抵抗率 ρ と長さ l に比例し、断面積 S に反比例します。", unit: "Ω" },
    { id: 84, category: "電磁気", name: "ジュール熱", formula: "Q = VIt", desc: "時間tの間に抵抗で発生する熱量（エネルギー損失）です。", unit: "J" },
    { id: 85, category: "電磁気", name: "電力（消費電力）", formula: "P = V I", desc: "電気器具が1秒あたりに消費する電気エネルギーの量です。", unit: "W" },
    { id: 86, category: "電磁気", name: "抵抗の直列合成", formula: "R = R₁ + R₂", desc: "抵抗を一本道に並べると、合計抵抗は足し算になります。", unit: "Ω" },
    { id: 87, category: "電磁気", name: "抵抗の並列合成", formula: "1/R = 1/R₁ + 1/R₂", desc: "迂回路を作るため電流が流れやすくなり、合成抵抗は小さくなります。", unit: "Ω" },
    { id: 88, category: "電磁気", name: "直線電流の磁場", formula: "H = I / 2πr", desc: "直線電流 I から距離 r の周囲に同心円状に生まれる磁場の強さです。", unit: "A/m" },
    { id: 89, category: "電磁気", name: "円形電流の中心磁場", formula: "H = I / 2r", unit: "A/m", desc: "半径rの円形電流の中心に生じる磁場の強さです。", unit: "A/m" },
    { id: 90, category: "電磁気", name: "アンペール力", formula: "F = I B l", desc: "磁束密度 B の中に置いた長さ l の導線に電流 I を流したときに受ける力です。", unit: "N" },
    { id: 91, category: "電磁気", name: "ローレンツ力", formula: "F = q v B", desc: "【実験3連動】磁場 B 中を速度 v で動く電荷 q が受ける、円運動を起こす力です。", unit: "N" },

    // ==========================================
    // 5. 原子（No.92 〜 No.101）
    // ==========================================
    { id: 92, category: "原子", name: "光子のエネルギー", formula: "E = h f", desc: "光を粒子（光子）として捉えたときのエネルギー。振動数 f に比例します。", unit: "J" },
    { id: 93, category: "原子", name: "光子の運動量", formula: "p = h / λ", desc: "質量ゼロの光子であっても、波長 λ に反比例した運動量を持ちます。", unit: "kg·m/s" },
    { id: 94, category: "原子", name: "光電方程式", formula: "h f = W + K_max", desc: "光子hfを金属にぶつけた際、仕事関数Wと電子の運動エネルギーに分配されます。", unit: "J" },
    { id: 95, category: "原子", name: "コンプトン効果（波長変化）", formula: "Δλ = (h/mc)(1-cosθ)", unit: "m", desc: "X線を物質に当てた時、散乱角θによって散乱X線の波長が伸びる現象の式です。", unit: "m" },
    { id: 96, category: "原子", name: "ド・ブロイ波長（物質波）", formula: "λ = h / mv", desc: "動く「物体」も、質量 m と速度 v に応じた波（波長 λ）の性質を持ちます。", unit: "m" },
    { id: 97, category: "原子", name: "ボアの量子条件", formula: "2πr = n λ", desc: "電子が原子核の周りを定常波として安定して回るための軌道長条件です。", unit: "なし" },
    { id: 98, category: "原子", name: "ボアの振動数条件", formula: "h ν = E_m - E_n", desc: "電子が軌道を飛び移る際、エネルギー差分の光（hν）を放出（吸収）します。", unit: "なし" },
    { id: 99, category: "原子", name: "崩壊の法則（半減期）", formula: "N = N₀(1/2)^(t / T)", desc: "放射性原子核が崩壊し、元の量が半分になる周期 T に基づく減少式です。", unit: "個" },
    { id: 100, category: "原子", name: "質量エネルギーの等価性", formula: "E = m c²", desc: "質量 m とエネルギー E は同等。質量が消滅すると莫大なエネルギーが出ます。", unit: "J" },
    { id: 101, category: "原子", name: "結合エネルギー（質量欠損）", formula: "ΔE = Δm · c²", desc: "【実験5連動】原子核が形成される際、失われた質量 Δm が強固な結合力になります。", unit: "J" }
];
