// 物理公式101選 完全データベース
const PHYSICS_FORMULAS = [
    // 1. 力学（No.1 〜 No.41）
    { id: 1, category: "力学", name: "平均の速度", formula: "v = Δx / Δt", desc: "位置の変化量を時間で割った速度の基本定義です。", unit: "m/s" },
    { id: 2, category: "力学", name: "平均の加速度", formula: "a = Δv / Δt", desc: "単位時間あたりの速度の変化割合を表します。", unit: "m/s²" },
    { id: 3, category: "力学", name: "等加速度直線運動（速度）", formula: "v = v₀ + at", desc: "加速する物体の時間tにおける速度を計算します。", unit: "m/s" },
    { id: 4, category: "力学", name: "等加速度直線運動（変位）", formula: "x = v₀t + 1/2 at²", desc: "加速する物体が進む距離（位置）を求めます。", unit: "m" },
    { id: 5, category: "力学", name: "等加速度直線運動（時間なし）", formula: "v² - v₀² = 2ax", desc: "時間tを含まない速度と位置の便利な関係式です。", unit: "なし" },
    { id: 6, category: "力学", name: "自由落下（速度）", formula: "v = gt", desc: "初速0で重力によって落下する物体の速度です。", unit: "m/s" },
    { id: 7, category: "力学", name: "自由落下（変位）", formula: "y = 1/2 * g * t²", desc: "落下し始めてからの距離を時間を基準に求めます。", unit: "m" },
    { id: 8, category: "力学", name: "鉛直投げ下ろし（速度）", formula: "v = v₀ + gt", desc: "下向きに初速をあたえて落とした物体の速度です。", unit: "m/s" },
    { id: 9, category: "力学", name: "鉛直投げ下ろし（変位）", formula: "y = v₀t + 1/2 * g * t²", desc: "投げ下ろしたおもりの落下距離を算出します。", unit: "m" },
    { id: 10, category: "力学", name: "鉛直投げ上げ（速度）", formula: "v = v₀ - gt", desc: "上向きに投げた物体の速度。最高点でゼロになります。", unit: "m/s" },
    { id: 11, category: "力学", name: "鉛直投げ上げ（変位）", formula: "y = v₀t - 1/2 * g * t²", desc: "投げ上げたおもりの高さを求めます。", unit: "m" },
    { id: 12, category: "力学", name: "斜方投射（水平位置）", formula: "x = v₀ * cosθ * t", desc: "斜めに投げた物体の、横方向の等速運動成分です。", unit: "m" },
    { id: 13, category: "力学", name: "斜方投射（鉛直位置）", formula: "y = v₀ * sinθ * t - 1/2 * g * t²", desc: "斜めに投げた物体の、縦方向の放物運動成分です。", unit: "m" },
    { id: 14, category: "力学", name: "フックの法則", formula: "F = kx", desc: "ばねの伸び縮みxに比例して発生する弾性力です。", unit: "N" },
    { id: 15, category: "力学", name: "運動方程式", formula: "ma = F", desc: "質量、加速度、受ける力の根本関係を示す物理の最重要式です。", unit: "N" },
    { id: 16, category: "力学", name: "重力の大きさ", formula: "W = mg", desc: "質量mの物体が地球から受ける重力の大きさです。", unit: "N" },
    { id: 17, category: "力学", name: "最大静止摩擦力", formula: "F = μN", desc: "物体が滑り出す直前の、摩擦力の限界値です。", unit: "N" },
    { id: 18, category: "力学", name: "動摩擦力", formula: "F = μ'N", desc: "滑っている物体にはたらく、速度によらず一定の摩擦力です。", unit: "N" },
    { id: 19, category: "力学", name: "圧力の定義", formula: "P = F / S", desc: "単位面積あたりにかかる、面を垂直に押す力です。", unit: "Pa" },
    { id: 20, category: "力学", name: "水圧", formula: "P = ρhg", desc: "水深hにおける水の重さによる圧力です。", unit: "Pa" },
    { id: 21, category: "力学", name: "浮力", formula: "F = ρVg", desc: "流体中の物体が押しのけた流体の重さと同じ上向きの力です。", unit: "N" },
    { id: 22, category: "力学", name: "力のモーメント", formula: "M = Fl", desc: "物体を回転させる力の能率。腕の長さlと力の積です。", unit: "N·m" },
    { id: 23, category: "力学", name: "重心", formula: "x = (m₁x₁ + m₂x₂) / (m₁ + m₂)", desc: "2つの物体の釣り合いの中心となる位置を求めます。", unit: "m" },
    { id: 24, category: "力学", name: "運動量", formula: "p = mv", desc: "物体の質量と速度の積で、運動の勢いを表します。", unit: "kg·m/s" },
    { id: 25, category: "力学", name: "力積", formula: "I = FΔt", desc: "力とそれを加えた時間の積で、運動量に変化を与えます。", unit: "N·s" },
    { id: 26, category: "力学", name: "運動量と力積", formula: "mv' - mv = FΔt", desc: "力積を受けた結果、運動量がどれだけ変化したかを示します。", unit: "なし" },
    { id: 27, category: "力学", name: "運動量保存則", formula: "m₁v₁ + m₂v₂ = 一定", desc: "衝突前後で外力がなければ全体の運動量の総和は変わりません。", unit: "なし" },
    { id: 28, category: "力学", name: "反発係数", formula: "e = - (v₁' - v₂') / (v₁ - v₂)", desc: "衝突前後の相対速度の比を表す係数（0〜1）です。", unit: "なし" },
    { id: 29, category: "力学", name: "仕事の定義", formula: "W = F s cosθ", desc: "加えた力と移動距離、およびそのなす角によるエネルギー移動です。", unit: "J" },
    { id: 30, category: "力学", name: "仕事率", formula: "P = W / t", desc: "1秒間あたりにこなした仕事の能率を表します。", unit: "W" },
    { id: 31, category: "力学", name: "運動エネルギー", formula: "K = 1/2 mv²", desc: "動いている物体が持つ、速度の2乗に比例するエネルギーです。", unit: "J" },
    { id: 32, category: "力学", name: "位置エネルギー(重力)", formula: "U = mgh", desc: "高い場所にある物体が持つ潜在的なエネルギーです。", unit: "J" },
    { id: 33, category: "力学", name: "位置エネルギー(弾性)", formula: "U = 1/2 kx²", desc: "引き伸ばされたばねに蓄えられているエネルギーです。", unit: "J" },
    { id: 34, category: "力学", name: "力学的エネルギー保存", formula: "K + U = 一定", desc: "保存力のみが働く場合、運動と位置エネルギーの和は不変です。", unit: "なし" },
    { id: 35, category: "力学", name: "角速度", formula: "ω = θ / t", desc: "円運動において、1秒間に回転する角度（ラジアン）です。", unit: "rad/s" },
    { id: 36, category: "力学", name: "円運動の速度", formula: "v = rω", desc: "回転半径rと角速度から、接線方向の速度を求めます。", unit: "m/s" },
    { id: 37, category: "力学", name: "向心加速度", formula: "a = rω² = v² / r", desc: "円運動を維持するため、常に中心に向かう加速度です。", unit: "m/s²" },
    { id: 38, category: "力学", name: "向心力", formula: "F = mrω²", desc: "円運動をさせるために中心向きに必要な力です。", unit: "N" },
    { id: 39, category: "力学", name: "ばね振り子の周期", formula: "T = 2π√(m / k)", desc: "ばねに吊るされたおもりが往復する1周期の時間を求めます。", unit: "s" },
    { id: 40, category: "力学", name: "単振り子の周期", formula: "T = 2π√(l / g)", desc: "ひもの長さlのおもりが微小振動するときの周期です。", unit: "s" },
    { id: 41, category: "力学", name: "万有引力の法則", formula: "F = G * M * m / r²", desc: "すべての質量間に働く、距離の2乗に反比例する引き合う力です。", unit: "N" },

    // 2. 熱力学（No.42 〜 No.53）
    { id: 42, category: "熱力学", name: "熱量と熱容量", formula: "Q = C * ΔT", desc: "物体全体の温度を変化させるのに必要な熱量です。", unit: "J" },
    { id: 43, category: "熱力学", name: "熱量と比熱", formula: "Q = m * c * ΔT", desc: "物質1gを1度上げる固有の能力（比熱）を用いた熱量式です。", unit: "J" },
    { id: 44, category: "熱力学", name: "熱膨張", formula: "l = l₀(1 + αt)", desc: "温度上昇によって金属などの長さが伸びる割合を示します。", unit: "m" },
    { id: 45, category: "熱力学", name: "ボイルの法則", formula: "P * V = 一定", desc: "温度が一定のとき、気体の圧力と体積は反比例します。", unit: "なし" },
    { id: 46, category: "熱力学", name: "シャルルの法則", formula: "V / T = 一定", desc: "圧力が一定のとき、気体の体積は絶対温度に比例します。", unit: "なし" },
    { id: 47, category: "熱力学", name: "理想気体の状態方程式", formula: "PV = nRT", desc: "気体のマクロな状態（P,V,T）と物質量を結ぶ極めて重要な式です。", unit: "なし" },
    { id: 48, category: "熱力学", name: "分子の平均運動エネルギー", formula: "1/2 mv² = 3/2 kT", desc: "気体分子1個の運動エネルギーは絶対温度だけで決まります。", unit: "J" },
    { id: 49, category: "熱力学", name: "内部エネルギー", formula: "U = 3/2 nRT", desc: "理想気体が内部に保持する熱運動エネルギーの総量です。", unit: "J" },
    { id: 50, category: "熱力学", name: "熱力学第一法則", formula: "ΔU = Q + W", desc: "エネルギー保存則。内部エネルギーは熱や仕事で変化します。", unit: "J" },
    { id: 51, category: "熱力学", name: "定圧変化の仕事", formula: "W = P * ΔV", desc: "圧力が一定のまま膨張したときに気体が外にする仕事です。", unit: "J" },
    { id: 52, category: "熱力学", name: "マイヤーの関係式", formula: "Cp - Cv = R", desc: "定圧モル比熱と定積モル比熱の差が気体定数になることを示します。", unit: "J/(mol·K)" },
    { id: 53, category: "熱力学", name: "熱効率", formula: "e = W / Q", desc: "取り込んだ全熱量のうち、どれだけ仕事に変換できたかの割合です。", unit: "なし" },

    // 3. 波動（No.54 〜 No.69）
    { id: 54, category: "波動", name: "波の基本式", formula: "v = f * λ", desc: "波の進む速度は、1秒間の振動数と波長の積になります。", unit: "m/s" },
    { id: 55, category: "波動", name: "周期と振動数", formula: "T = 1 / f", desc: "1回振動する時間（周期）と1秒の振動数は逆数の関係です。", unit: "s" },
    { id: 56, category: "波動", name: "屈折の法則", formula: "sin i / sin r = v₁ / v₂", desc: "異なる媒質に突入する波の、角度と速度の変化の法則です。", unit: "なし" },
    { id: 57, category: "波動", name: "絶対屈折率", formula: "n = c / v", desc: "真空中に対する、その物質中の光の減速比率です。", unit: "なし" },
    { id: 58, category: "波動", name: "全反射の臨界角", formula: "sin i = n₂ / n₁", desc: "光が完全に跳ね返る（全反射）が起き始める限界の入射角です。", unit: "なし" },
    { id: 59, category: "波動", name: "うなりの振動数", formula: "f = |f₁ - f₂|", desc: "わずかに違う音が重なるとき、1秒間に聞こえる音の強弱の回数です。", unit: "Hz" },
    { id: 60, category: "波動", name: "弦を伝わる波の速さ", formula: "v = √(S / ρ)", desc: "ひもの張力Sが強いほど、線密度が小さいほど波は速く伝わります。", unit: "m/s" },
    { id: 61, category: "波動", name: "弦の固有振動数", formula: "f = n * v / 2L", desc: "ピンと張った長さLの弦が共鳴して鳴らす音の周波数です。", unit: "Hz" },
    { id: 62, category: "波動", name: "閉管の固有振動数", formula: "f = (2k-1) * v / 4L", desc: "片方が閉じた筒の中で空気が共鳴する周波数です（奇数倍音）。", unit: "Hz" },
    { id: 63, category: "波動", name: "開管の固有振動数", formula: "f = n * v / 2L", desc: "両端が開いた筒の中で空気が共鳴する周波数です（全整数倍音）。", unit: "Hz" },
    { id: 64, category: "波動", name: "音速", formula: "V = 331.5 + 0.6t", desc: "空気中の音の速さは、気温tが上がると速くなります。", unit: "m/s" },
    { id: 65, category: "波動", name: "ドップラー効果", formula: "f' = f * (V - v_o) / (V - v_s)", desc: "救急車（音源）や自分が動くことで音の高さが変わる現象です。", unit: "Hz" },
    { id: 66, category: "波動", name: "凸レンズの公式", formula: "1/a + 1/b = 1/f", desc: "レンズから物体、像、焦点までの距離を結ぶ光学の基本公式です。", unit: "なし" },
    { id: 67, category: "波動", name: "レンズの倍率", formula: "m = b / a", desc: "出来上がる像の大きさが元の何倍になるかを表します。", unit: "なし" },
    { id: 68, category: "波動", name: "ヤングの実験", formula: "d * x / L = m * λ", desc: "2つのスリットを通った光が、干渉して縞模様を作る明線条件です。", unit: "なし" },
    { id: 69, category: "波動", name: "回折格子", formula: "d * sinθ = m * λ", desc: "無数の細いスリットを持つ板に光を通した時の強め合い条件です。", unit: "なし" },

    // 4. 電磁気（No.70 〜 No.91）
    { id: 70, category: "電磁気", name: "クーロンの法則", formula: "F = k * q₁ * q₂ / r²", desc: "電荷同士に働く力。電気量の積に比例し、距離の2乗に反比例します。", unit: "N" },
    { id: 71, category: "電磁気", name: "電場", formula: "E = F / q", desc: "空間の電気的な強さ。1Cの電荷が受ける静電気力に相当します。", unit: "N/C" },
    { id: 72, category: "電磁気", name: "点電荷の電場", formula: "E = k * Q / r²", desc: "電気量Qの球体が、距離rの場所に作り出す電場の強さです。", unit: "N/C" },
    { id: 73, category: "電磁気", name: "電位の定義", formula: "V = U / q", desc: "電気的な位置エネルギーの「高さ」を1Cあたりで定義したものです。", unit: "V" },
    { id: 74, category: "電磁気", name: "点電荷の電位", formula: "V = k * Q / r", desc: "点電荷の周囲に形成される、距離に反比例する電位の山の高さです。", unit: "V" },
    { id: 75, category: "電磁気", name: "一様電場と電圧", formula: "V = E * d", desc: "平行板コンデンサー内部などの均一な電場における、電圧と距離の式です。", unit: "V" },
    { id: 76, category: "電磁気", name: "コンデンサーの電気量", formula: "Q = C * V", desc: "容量Cのコンデンサーに電圧Vをかけた時に充電される電荷量です。", unit: "C" },
    { id: 77, category: "電磁気", name: "平行板コンデンサーの容量", formula: "C = ε * S / d", desc: "極板の面積Sに比例し、間隔dに反比例する容量計算式です。", unit: "F" },
    { id: 78, category: "電磁気", name: "静電エネルギー", formula: "U = 1/2 C * V²", desc: "充電されたコンデンサー内部に蓄えられている電気エネルギーです。", unit: "J" },
    { id: 79, category: "電磁気", name: "コンデンサー並列合成", formula: "C = C₁ + C₂", desc: "並列に繋ぐと、全体の容量は単純な足し算になります。", unit: "F" },
    { id: 80, category: "電磁気", name: "コンデンサー直列合成", formula: "1/C = 1/C₁ + 1/C₂", desc: "直列に繋ぐと、合成容量は個々のものより小さくなります。", unit: "F" },
    { id: 81, category: "電磁気", name: "電流の定義", formula: "I = q / t", desc: "回路の断面を1秒間に通過していく電気の量です。", unit: "A" },
    { id: 82, category: "電磁気", name: "オームの法則", formula: "V = R * I", desc: "抵抗に電流を流すために必要な電圧の基本比例関係式です。", unit: "V" },
    { id: 83, category: "電磁気", name: "電気抵抗", formula: "R = ρ * l / S", desc: "導線の抵抗値。材料固有の抵抗率、長さに比例し、断面積に反比例します。", unit: "Ω" },
    { id: 84, category: "電磁気", name: "ジュール熱", formula: "Q = V * I * t", desc: "抵抗に電流が流れたとき、電気エネルギーが熱に化ける量です。", unit: "J" },
    { id: 85, category: "電磁気", name: "消費電力", formula: "P = V * I", desc: "電気器具が1秒間に消費、または生み出す電気エネルギー量です。", unit: "W" },
    { id: 86, category: "電磁気", name: "抵抗の直列合成", formula: "R = R₁ + R₂", desc: "直列回路では全体の抵抗値はそれぞれの和になります。", unit: "Ω" },
    { id: 87, category: "電磁気", name: "抵抗の並列合成", formula: "1/R = 1/R₁ + 1/R₂", desc: "道が増えるため電流が流れやすくなり、全体の抵抗は小さくなります。", unit: "Ω" },
    { id: 88, category: "電磁気", name: "直線電流の磁場", formula: "H = I / (2πr)", desc: "まっすぐな導線に電流を流したとき、周囲に円状にできる磁場の強さです。", unit: "A/m" },
    { id: 89, category: "電磁気", name: "円形電流の磁場", formula: "H = I / (2r)", desc: "円状に巻いた電流の中心点に発生する磁場の強さです。", unit: "A/m" },
    { id: 90, category: "電磁気", name: "アンペール力", formula: "F = I * B * l", desc: "磁場の中にある導線に電流を流したときに、導線全体が受ける力です。", unit: "N" },
    { id: 91, category: "電磁気", name: "ローレンツ力", formula: "F = q * v * B", desc: "磁場の中を動く、電子や陽子などの「動く1個の電荷」が受ける力です。", unit: "N" },

    // 5. 原子（No.92 〜 No.101）
    { id: 92, category: "原子", name: "光子のエネルギー", formula: "E = h * f", desc: "光を粒子として見た時のエネルギー。振動数fに比例します。", unit: "J" },
    { id: 93, category: "原子", name: "光子の運動量", formula: "p = h / λ", desc: "質量ゼロの光子でも、波長に反比例した「勢い」を持ちます。", unit: "kg·m/s" },
    { id: 94, category: "原子", name: "光電方程式", formula: "h*f = W + K", desc: "光を当てて電子を叩き出す現象の、エネルギー分配の式です。", unit: "J" },
    { id: 95, category: "原子", name: "コンプトン効果", formula: "Δλ = h/(mc) * (1-cosθ)", desc: "X線が電子に衝突して跳ね返るとき、波長が伸びる公式です。", unit: "m" },
    { id: 96, category: "原子", name: "物質波（ド・ブロイ波長）", formula: "λ = h / (m * v)", desc: "電子や野球ボールなど、あらゆる動く物体が持つ「波」としての波長です。", unit: "m" },
    { id: 97, category: "原子", name: "ボアの量子条件", formula: "2πr = n * λ", desc: "電子が原子核の周りを、定常波として安定して存在するための軌道条件です。", unit: "なし" },
    { id: 98, category: "原子", name: "ボアの振動数条件", formula: "h*f = E₂ - E₁", desc: "電子が軌道を飛び移るとき、エネルギー差に等しい光を出す（吸う）条件です。", unit: "なし" },
    { id: 99, category: "原子", name: "崩壊の法則（半減期）", formula: "N = N₀ * (1/2)^(t/T)", desc: "放射性物質が崩壊し、量が半分になる周期Tに基づいた減少式です。", unit: "個" },
    { id: 100, category: "原子", name: "質量エネルギーの等価性", formula: "E = m * c²", desc: "質量とエネルギーは全く同じもの。質量が消えると莫大な光が出ます。", unit: "J" },
    { id: 101, category: "原子", name: "結合エネルギー", formula: "ΔE = Δm * c²", desc: "原子核が合体して固まるとき、失われた質量が強い結合のエネルギーになります。", unit: "J" }
];
